# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
permalink: /blog/:year/:month/:day/:title/

source: _source
destination: _site

paginate: 10          # Posts per page on the blog index
paginate_path: "blog/page/:num/"  # Directory base for pagination URLs eg. /blog/page/2/
category_dir: blog/categories/

recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase